# Generated by Django 5.1.3 on 2024-11-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("rfc", models.CharField(max_length=13)),
                ("fecha", models.DateField()),
                ("importe", models.DecimalField(decimal_places=2, max_digits=10)),
                ("aprobado", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="CreditRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("rfc", models.CharField(max_length=13, unique=True)),
                ("fecha_nacimiento", models.DateField()),
                (
                    "importe_solicitado",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "ingresos_mensuales",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("historial_crediticio", models.BooleanField(default=False)),
                ("solicitud_en_proceso", models.BooleanField(default=False)),
                ("aprobado", models.BooleanField(blank=True, null=True)),
                ("razon_rechazo", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
