# Generated by Django 5.1.3 on 2024-11-28 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credits", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CreditHistory",
        ),
        migrations.AddField(
            model_name="creditrequest",
            name="fecha_solicitud",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="creditrequest",
            name="rfc",
            field=models.CharField(max_length=13),
        ),
    ]
